#if !canImport(ObjectiveC)
import XCTest

extension CypherPoetReduxUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CypherPoetReduxUtilsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CypherPoetReduxUtilsTests.__allTests__CypherPoetReduxUtilsTests),
    ]
}
#endif
